version: "3"
services:
  web:
    image: localhost:5000/jsp-frontend
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.15"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8092:8090"
    networks:
      - webnet
networks:
  webnet: